apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quick-note-config
  namespace: development
data:
  config.yaml: |
    server:
      PORT: 3000
    database:
      URL: "postgres://<url>"
    quick-note:
      VERSION: "0.0.1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-note
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quick-note-server
  template:
    metadata:
      labels:
        run: quick-note-server
    spec:
      containers:
        - name: quick-note
          image: ghcr.io/sithumonline/quick-note:latest
          args: ["server"]
          volumeMounts:
            - name: quick-note-config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: quick-note-config-volume
          configMap:
            name: quick-note-config
---
apiVersion: v1
kind: Service
metadata:
  name: quick-note-entrypoint
  namespace: development
spec:
  type: NodePort
  selector:
    run: quick-note-server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30800
